"use client"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: wojteX (https://sketchfab.com/wojteX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/esp32-wroom-32-low-poly-photorealistic-af0851c326ef4cbaa42439f801acbe98
Title: ESP32 WROOM 32 - Low Poly Photorealistic
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/esp32_wroom_32_-_low_poly_photorealistic/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={1.066}>
          <mesh geometry={nodes.Cube025_ESP_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube025_ESP_SIDE_0.geometry} material={materials.ESP_SIDE} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/esp32_wroom_32_-_low_poly_photorealistic/scene.gltf')
