import type { Metadata } from "next";
import { soDoSans } from "@/lib/fonts";
import "./globals.css";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="scroll-smooth">
      <body className={`${soDoSans.className} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex flex-col flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
